theme: jekyll-theme-minimal
title: Sample github pages site
description: Welcome to Data 104 Social Media Web Analytics
url:  https://euribe98.github.io/Data104
author: E. Uribe
plugins:
  - jekyll-seo-tag
google_analytics: 'UA-177361370-1'
